
services:
  - docker


script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed rolteame/udagram-api-feed:v1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user sudkul/udagram-api-user:v1
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend sudkul/udagram-frontend:v1
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy rolteame/reverseproxy:v1


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push rolteame/udagram-api-feed:v1
  - docker push rolteame/udagram-api-user:v1
  - docker push rolteame/udagram-frontend:v1
  - docker push rolteame/reverseproxy:v1